#!/bin/sh
# Disable hardware TC offload on physical NICs

IFACES="eth0 eth1 eth2 eth3"

for IFACE in $IFACES; do
    [ "$INTERFACE" = "$IFACE" ] || continue
    ethtool -K "$IFACE" hw-tc-offload off 2>/dev/null
done

exit 0
