name: Sync from upstream

on:
  schedule:
    - cron: '0 3 * * *'  # 每天凌晨3点自动执行
  workflow_dispatch:      # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Add upstream
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/wukongdaily/AutoBuildImmortalWrt.git
          git fetch upstream

      - name: Try merge upstream/master
        run: |
          set -e
          git checkout master
          git merge upstream/master -m "Merge upstream"
        continue-on-error: true

      - name: Force pull if merge failed
        if: failure()
        run: |
          echo "Merge failed, performing force sync..."
          git fetch upstream
          git reset --hard upstream/master

      - name: Push changes
        run: |
          git push origin master --force
